import React from "react";
import "./Stylesheets//Register.css";

function About() {
  return (
    <div className="about">
      <div class="container-fluid" className="about1">
      
        <h1 class="font-weight-light h1style">Project Background & Inspiration</h1>
            <p>
              IN MAY, THE PASTOR OF MY CHURCH FELT LEAD TO TAKE ACTS 4:32-35 SERIOUSLY AND PRACTICALLY. ALL THE BELIEVERS WERE ONE IN HEART AND MIND. NO ONE CLAIMED THAT ANY OF THEIR POSSESSIONS WAS THEIR OWN, BUT THEY SHARED EVERYTHING THEY HAD. … AND GOD’S GRACE WAS SO POWERFULLY AT WORK IN THEM ALL THAT THERE WERE NO NEEDY PERSONS AMONG THEM. FOR FROM TIME TO TIME THOSE WHO OWNED LAND OR HOUSES SOLD THEM, BROUGHT THE MONEY FROM THE SALES AND PUT IT AT THE APOSTLES’ FEET, AND IT WAS DISTRIBUTED TO ANYONE WHO HAD NEED
              TO HELP FACILITATE CONNECTING PEOPLE WITH NEEDS TO THOSE THAT WERE WANTING TO HELP, WE CREATED A SURVEY FORM THAT PEOPLE WITH NEEDS WOULD FILL OUT AND THEN CREATED A SPREADSHEET TO LIST ALL THE NEEDS THAT OTHERS COULD VIEW. THEN WE CONNECTED THE MATCHES BY EMAILING THEM BOTH INTRODUCING THEM TO EACH OTHER AND GIVING SOME INSTRUCTION ON HOW TO MOVE FORWARD.
              WE SAW INCREDIBLE TESTIMONIES COME OUT OF THIS SIMPLE PROCESS! OVER $150,000 IN DEBT (MUCH OF IT WAS MEDICAL DEBT) WAS PAID OFF! SEVERAL PEOPLE MENTIONED THAT THROUGH THIS PROCESS THEY HAVE DEVELOPED DEEP NEW FRIENDSHIPS WITH THOSE THAT THEY HELPED OR THOSE THAT HELPED THEM. SEVERAL CARS WERE GIVEN TO PEOPLE WHO NEEDED THEM. EMPLOYERS WERE CONNECTED WITH PEOPLE LOOKING FOR JOBS. ONE FAMILY SOLD THEIR $25,000 BOAT AND GAVE ALL THE PROCEEDS AWAY!
              ONE WOMAN HAD STRUGGLED WITH TERRIBLE TEETH HERE WHOLE LIFE. HER MOLARS WOULD LITERALLY CRUMBLE AND FALL APART. SHE HAD TWO MOLARS THAT HAD CRACKED AND NEEDED EMERGENCY CROWNS THAT SHE COULD NOT AFFORD. A FAMILY SAW HER NEED POSTED (SHE DIDN’T MENTION IN HER POST THAT SHE HAD MULTIPLE OTHER TEETHE THAT WERE IN DESPERATE NEED OF CROWNS. THE FAMILY FOUND OUT ABOUT THE OTHER TEETH AND PAID FOR ALL OF THEM TO RECEIVE NEW CROWNS (OVER $10,000!)
              THERE WAS A MAN FROM A NATION IN THE MIDDLE EAST WHO HAD MOVED TO THE USA FOR WORK BUT WAS UNABLE TO AFFORD TO BRING HIS FAMILY WITH HIM AND HAD BEEN SENDING MONEY BACK TO THEM BUT HADN'T SEEN HIS WIFE AND KIDS FOR OVER A YEAR! HE HAD BEEN ATTENDING OUR CHURCH FOR A WHILE AND SOMEONE SAW HIS NEED AND PAID FOR THE AIRFARE AND VISA PROCESS FOR HIS ENTIRE FAMILY AND THEY WERE REUNITED!
              IT’S BEEN ABSOLUTELY ASTOUNDING TO SEE THE LIVES THAT WERE CHANGED THROUGH THIS SIMPLE PROCESS AND THE BODY OF CHRIST CARING FOR ONE ANOTHER IN SUCH TANGIBLE WAYS. IT WAS SUCH AN INCREDIBLE PROCESS TO WITNESS.
            </p>
          </div>
    </div>
  );
}

export default About;